# Generated by Django 2.2 on 2019-04-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
